"""Tests for the parse_compile_to_requirements helper function."""

from uv_audit.environment_handler import parse_compile_to_requirements


def test_parse_compile_to_requirements_typical_output():
    """Verify that a uv pip compile output is parsed into a list of 'name==version' strings."""
    # arrange
    compile_output = (
        "absl-py==2.4.0\n"
        "    # via ortools\n"
        "annotated-doc==0.0.4\n"
        "    # via fastapi\n"
        "requests==2.32.3\n"
        "    # via reseller-api (services/reseller/core/pyproject.toml)\n"
    )

    # act
    result = parse_compile_to_requirements(compile_output)

    # assert
    assert result == [
        "absl-py==2.4.0",
        "annotated-doc==0.0.4",
        "requests==2.32.3",
    ]


def test_parse_compile_to_requirements_empty_input():
    """Verify that an empty string returns an empty list."""
    # act
    result = parse_compile_to_requirements("")

    # assert
    assert result == []


def test_parse_compile_to_requirements_skips_header_and_blank_lines():
    """Verify that header comments, blank lines, and trailing comments are ignored."""
    # arrange
    compile_output = (
        "# This file was autogenerated by uv\n"
        "# via the following command:\n"
        "#    uv pip compile pyproject.toml\n"
        "\n"
        "click==8.2.1\n"
        "\n"
        "requests==2.32.3  # pinned\n"
    )

    # act
    result = parse_compile_to_requirements(compile_output)

    # assert
    assert result == ["click==8.2.1", "requests==2.32.3"]
