name: uv-audit

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - uses: ./
        with:
          uv_audit_source: ${{ github.workspace }}
          exclude: |
            .venv
            venv
            .tox
            node_modules
            .git
            dist
            build
            site-packages
            tests/fixtures
          ignore_vulns: |
            PYSEC-2026-161
          fail_on_vuln: "false"
